"""Demo migration generated by setup.sh.

The Deploy Party PR validator detects any path matching
`<app>/migrations/<file>.py` as migration-bearing and forces a solo
party. This file exists purely to exercise that path; the operations
list is empty so applying it is a no-op.
"""
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []
    operations = []
